name: manbitesfilm
favicon: null
layout_spectrum: 0.36845
typography_spectrum: 0.74891
title: manbitesfilm
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#5c4016'
    - '#ffffff'
    - '#ecc200'
    - '#0083ca'
  brandStrength: 0.75
  lightness: 0.125
  saturation: 0
  rhythmicContrast: 1
purpose: []
